# Generated by Django 4.1.7 on 2023-05-13 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='capa')),
                ('name', models.CharField(max_length=100)),
                ('auth', models.CharField(max_length=30)),
                ('cd_auth', models.CharField(blank=True, max_length=30, null=True)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('borrowed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'verbose_name': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_responsible', models.CharField(blank=True, max_length=30, null=True)),
                ('borrowing_date', models.DateTimeField(default=datetime.datetime(2023, 5, 13, 16, 24, 17, 253496))),
                ('book_return', models.DateTimeField(blank=True, null=True)),
                ('available', models.CharField(blank=True, choices=[('B', 'Bad'), ('R', 'Regular'), ('G', 'Good'), ('A', 'Awesome')], max_length=1, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
