# Generated by Django 4.2.6 on 2023-10-06 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='borrowing_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 12, 20, 36, 614997)),
        ),
    ]
